# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

environment:
  matrix:
    - nodejs_version: 0.12

build: off
deploy: off

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  - npm install -g grunt-cli
  - npm install
  - grunt setup

test_script:
  - npm test
